# Generated by Django 2.0.7 on 2018-09-10 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dj_gymnasiums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='category name')),
                ('img', models.CharField(max_length=128, verbose_name='category image name')),
                ('min_age', models.PositiveSmallIntegerField(verbose_name='category minimal age')),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='category maximal age')),
                ('summary', models.CharField(max_length=512, verbose_name='category summary')),
                ('description', markdownx.models.MarkdownxField(verbose_name='category description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='license person first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='license person last name')),
                ('sex', models.CharField(choices=[('MA', 'Male'), ('FE', 'Female')], max_length=2, verbose_name='sex')),
                ('birthday', models.DateField(verbose_name='birthday')),
                ('license_number', models.CharField(blank=True, max_length=20, verbose_name='license number')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'license',
                'verbose_name_plural': 'licenses',
                'ordering': ('team', 'first_name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_practice', models.PositiveSmallIntegerField(choices=[(0, 'Practice'), (1, 'Match')], verbose_name='Practice type')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Practice day')),
                ('start', models.TimeField(verbose_name='Practice starting time')),
                ('end', models.TimeField(verbose_name='Practice starting time')),
                ('gymnasium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_gymnasiums.Gymnasium')),
            ],
            options={
                'verbose_name': 'practice',
                'verbose_name_plural': 'practices',
                'ordering': ('day',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Team name')),
                ('level', models.CharField(choices=[('FSGT 6x6', (('OR', 'Gold'), ('ARG', 'Silver'), ('BRO', 'Bronze'))), ('FSGT 4x4', (('HAR', 'Hard'), ('MED', 'Medium'), ('EAS', 'Easy'))), ('FFVB', (('N1', 'Elite'), ('N2', 'National 2'), ('R1', 'Regional 1'), ('R2', 'Regional 2'), ('R3', 'Regional 3'), ('DEP', 'Departemental'))), ('Pleasure', (('PLE', 'Pleasure'),))], max_length=3, verbose_name='Level')),
                ('sex', models.CharField(choices=[('MA', 'Male'), ('MI', 'Mixed'), ('FE', 'Female')], max_length=2, verbose_name='Sexe')),
                ('url', models.URLField(verbose_name='Competition URL')),
                ('description', markdownx.models.MarkdownxField(blank=True, verbose_name='team description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_sports_manager.Category')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
                'ordering': ('sex', 'level', 'name'),
            },
        ),
        migrations.AddField(
            model_name='practice',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_sports_manager.Team'),
        ),
        migrations.AddField(
            model_name='license',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_sports_manager.Team'),
        ),
    ]
