# Generated by Django 2.0.7 on 2018-09-11 07:00

import dj_sports_manager.models
import dj_sports_manager.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_sports_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='img',
            field=models.ImageField(blank=True, storage=dj_sports_manager.storage.OverwriteStorage(), upload_to=dj_sports_manager.models.image_upload_to, verbose_name='team img'),
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, storage=dj_sports_manager.storage.OverwriteStorage(), upload_to=dj_sports_manager.models.image_upload_to, verbose_name='category img'),
        ),
        migrations.AlterField(
            model_name='team',
            name='level',
            field=models.CharField(choices=[('FSGT 6x6', (('OR', 'Gold'), ('ARG', 'Silver'), ('BRO', 'Bronze'))), ('FSGT 4x4', (('HAR', 'Hard'), ('MED', 'Medium'), ('EAS', 'Easy'))), ('FFVB', (('N1', 'Elite'), ('N2', 'National 2'), ('R1', 'Regional 1'), ('R2', 'Regional 2'), ('R3', 'Regional 3'), ('DEP', 'Departemental'))), ('Pleasure', (('PLE', 'Pleasure'),))], max_length=3, verbose_name='team level'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=128, verbose_name='team name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='sex',
            field=models.CharField(choices=[('MA', 'Male'), ('MI', 'Mixed'), ('FE', 'Female')], max_length=2, verbose_name='team sex'),
        ),
        migrations.AlterField(
            model_name='team',
            name='url',
            field=models.URLField(verbose_name='team competition URL'),
        ),
    ]
