# Generated by Django 2.0.7 on 2019-01-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_sports_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ('player',), 'verbose_name': 'license', 'verbose_name_plural': 'licenses'},
        ),
        migrations.RemoveField(
            model_name='license',
            name='team',
        ),
        migrations.AddField(
            model_name='license',
            name='team',
            field=models.ManyToManyField(blank=True, to='dj_sports_manager.Team'),
        ),
    ]
