# Generated by Django 2.0.7 on 2018-09-13 14:59

import dj_sports_manager.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dj_sports_manager', '0002_auto_20180911_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='certif',
            field=models.FileField(blank=True, upload_to=dj_sports_manager.models.image_upload_to, verbose_name='license medical certification'),
        ),
        migrations.AddField(
            model_name='license',
            name='certif_valid',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Certification not uploaded'), (1, 'Certification in validation'), (2, 'Certification valid'), (3, 'Certification rejected')], default=0, verbose_name='license medical certification validation'),
        ),
        migrations.AddField(
            model_name='license',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='licence creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='license',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='licence payed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='license',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='licence last modification date'),
        ),
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_captain', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='is_recruiting',
            field=models.BooleanField(default=True, verbose_name='team recruitement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='summary',
            field=models.TextField(max_length=512, verbose_name='category summary'),
        ),
        migrations.AlterField(
            model_name='license',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='licensee first name'),
        ),
        migrations.AlterField(
            model_name='license',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='licensee last name'),
        ),
        migrations.AlterField(
            model_name='license',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dj_sports_manager.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='level',
            field=models.CharField(choices=[('FSGT 6x6', (('OR', 'Gold'), ('ARG', 'Silver'), ('BRO', 'Bronze'))), ('FSGT 4x4', (('HAR', 'Hard'), ('MED', 'Medium'), ('EAS', 'Easy'))), ('FFVB', (('N1F', 'Elite Female'), ('N2F', 'National 2 Female'), ('R1F', 'Regional 1 Female'), ('R2F', 'Regional 2 Female'), ('R3F', 'Regional 3 Female'), ('DEPF', 'Departemental Female'), ('N1M', 'Elite Male'), ('N2M', 'National 2 Male'), ('R1M', 'Regional 1 Male'), ('R2M', 'Regional 2 Male'), ('R3M', 'Regional 3 Male'), ('DEPM', 'Departemental Male')))], max_length=4, verbose_name='team level'),
        ),
        migrations.AlterField(
            model_name='team',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_trainer', to=settings.AUTH_USER_MODEL),
        ),
    ]
