# Generated by Django 2.0.7 on 2018-09-14 06:39

from django.db import migrations, models
from django.utils.text import slugify


def slugify_category_name(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Category = apps.get_model('dj_sports_manager', 'Category')
    for category in Category.objects.all():
        category.slug = slugify(category.name)
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dj_sports_manager', '0003_auto_20180913_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=128, null=True, verbose_name='category slug'),
        ),
        migrations.RunPython(slugify_category_name),
    ]
