# Generated by Django 2.0.7 on 2018-09-14 07:13

from django.db import migrations, models
from django.utils.text import slugify


def slugify_team_name(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Team = apps.get_model('dj_sports_manager', 'Team')
    for team in Team.objects.all():
        team.slug = slugify(team.name)
        team.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dj_sports_manager', '0004_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(max_length=128, null=True, verbose_name='team slug'),
        ),
        migrations.RunPython(slugify_team_name)
    ]
