# Generated by Django 2.0.7 on 2018-09-14 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_sports_manager', '0005_team_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='captain',
        ),
        migrations.AddField(
            model_name='license',
            name='is_captain',
            field=models.BooleanField(default=False, verbose_name='is team captain'),
        ),
        migrations.AlterField(
            model_name='team',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
