# Generated by Django 2.0.7 on 2018-09-20 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_gymnasiums', '0001_initial'),
        ('dj_sports_manager', '0006_auto_20180914_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_time_slot', models.PositiveSmallIntegerField(choices=[(0, 'Practice'), (1, 'Match')], verbose_name='time slot type')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='time slot day')),
                ('start', models.TimeField(verbose_name='time slot starting time')),
                ('end', models.TimeField(verbose_name='time slot starting time')),
                ('gymnasium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_gymnasiums.Gymnasium')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_sports_manager.Team')),
            ],
            options={
                'verbose_name': 'practice',
                'verbose_name_plural': 'practices',
                'ordering': ('day',),
            },
        ),
        migrations.RemoveField(
            model_name='practice',
            name='gymnasium',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='team',
        ),
        migrations.DeleteModel(
            name='Practice',
        ),
    ]
