# Generated by Django 2.0.7 on 2018-09-20 14:53

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_sports_manager', '0007_auto_20180920_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=markdownx.models.MarkdownxField(verbose_name='team description'),
        ),
    ]
