# Generated by Django 2.0.7 on 2018-09-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_sports_manager', '0008_auto_20180920_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='level',
            field=models.CharField(choices=[('FSGT 6x6', (('GOL', 'Gold'), ('SIL', 'Silver'), ('BRO', 'Bronze'))), ('FSGT 4x4', (('HAR', 'Hard'), ('MED', 'Medium'), ('EAS', 'Easy'))), ('FFVB', (('N1F', 'Elite Female'), ('N2F', 'National 2 Female'), ('R1F', 'Regional 1 Female'), ('R2F', 'Regional 2 Female'), ('R3F', 'Regional 3 Female'), ('DEPF', 'Departemental Female'), ('N1M', 'Elite Male'), ('N2M', 'National 2 Male'), ('R1M', 'Regional 1 Male'), ('R2M', 'Regional 2 Male'), ('R3M', 'Regional 3 Male'), ('DEPM', 'Departemental Male')))], max_length=4, verbose_name='team level'),
        ),
    ]
