# Config file for automatic testing at travis-ci.org
sudo: false
notifications:
  email: false

language: python

matrix:
  fast_finish: true
  include:
    - python: 3.5
      env: TOXENV=py35-django20
    - python: 3.5
      env: TOXENV=py35-django21
    - python: 3.6
      env: TOXENV=py36-django20
    - python: 3.6
      env: TOXENV=py36-django21
    - python: 3.7-dev
      env: TOXENV=py37-django20
    - python: 3.7-dev
      env: TOXENV=py37-django21
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=isort

services:
  - rabbitmq

install:
  - pip install tox codecov

# command to run tests using coverage, e.g. python setup.py test
script:
  - tox -e $TOXENV

after_success:
  - codecov -e TOXENV
