# -*- coding: utf-8 -*-
"""Urls."""

from django.urls import path

from . import views


app_name = 'dj_sports_manager'
urlpatterns = [
    path("category/",
         view=views.CategoryListView.as_view(),
         name='categories-list',
         ),
    path("category/create",
         view=views.CategoryCreateView.as_view(),
         name='category-create',
         ),
    path("category/<str:name>",
         view=views.CategoryDetailView.as_view(),
         name='category-detail',
         ),
    path("category/<str:name>/update",
         view=views.CategoryUpdateView.as_view(),
         name='category-detail',
         ),
    path("category/<str:name>/delete",
         view=views.CategoryDeleteView.as_view(),
         name='category-detail',
         ),
    path("team/",
         view=views.TeamListView.as_view(),
         name='teams-list',
         ),
    path("team/create",
         view=views.TeamCreateView.as_view(),
         name='team-create',
         ),
    path("team/<int:pk>",
         view=views.TeamDetailView.as_view(),
         name='team-detail',
         ),
    path("team/<int:pk>/update",
         view=views.TeamUpdateView.as_view(),
         name='team-detail',
         ),
    path("team/<int:pk>/delete",
         view=views.TeamDeleteView.as_view(),
         name='team-detail',
         ),
    path("practice/",
         view=views.PracticeListView.as_view(),
         name='practices-list',
         ),
    path("practice/create",
         view=views.PracticeCreateView.as_view(),
         name='practice-create',
         ),
    path("practice/<int:pk>",
         view=views.PracticeDetailView.as_view(),
         name='practice-detail',
         ),
    path("practice/<int:pk>/update",
         view=views.PracticeUpdateView.as_view(),
         name='practice-detail',
         ),
    path("practice/<int:pk>/delete",
         view=views.PracticeDeleteView.as_view(),
         name='practice-detail',
         ),
    path("license/",
         view=views.TeamListView.as_view(),
         name='licenses-list',
         ),
    path("license/create",
         view=views.TeamCreateView.as_view(),
         name='license-create',
         ),
    path("license/<int:pk>",
         view=views.TeamDetailView.as_view(),
         name='license-detail',
         ),
    path("license/<int:pk>/update",
         view=views.TeamUpdateView.as_view(),
         name='license-detail',
         ),
    path("license/<int:pk>/delete",
         view=views.TeamDeleteView.as_view(),
         name='license-detail',
         ),
]
