# -*- coding: utf-8 -*-
"""Urls."""

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views


app_name = 'dj-sports-manager'
urlpatterns = [
    path("category/",
         view=views.CategoryListView.as_view(),
         name='categories-list',
         ),
    path("category/create",
         view=views.CategoryCreateView.as_view(),
         name='category-create',
         ),
    path("category/<str:slug>",
         view=views.CategoryDetailView.as_view(),
         name='category-detail',
         ),
    path("category/<str:slug>/update",
         view=views.CategoryUpdateView.as_view(),
         name='category-update',
         ),
    path("category/<str:slug>/delete",
         view=views.CategoryDeleteView.as_view(),
         name='category-delete',
         ),
    path("team/",
         view=views.TeamListView.as_view(),
         name='teams-list',
         ),
    path("team/create",
         view=views.TeamCreateView.as_view(),
         name='team-create',
         ),
    path("team/<str:slug>",
         view=views.TeamDetailView.as_view(),
         name='team-detail',
         ),
    path("team/<str:slug>/update",
         view=views.TeamUpdateView.as_view(),
         name='team-update',
         ),
    path("team/<str:slug>/delete",
         view=views.TeamDeleteView.as_view(),
         name='team-delete',
         ),
    path("team/<str:slug>/practice/",
         view=views.TeamPracticeListView.as_view(),
         name='practices-list',
         ),
    path("team/<str:slug>/practice/create",
         view=views.TeamPracticeCreateView.as_view(),
         name='practice-create',
         ),
    path("team/<str:slug>/practice/<int:pk>",
         view=views.TeamPracticeDetailView.as_view(),
         name='practice-detail',
         ),
    path("team/<str:slug>/practice/<int:pk>/update",
         view=views.TeamPracticeUpdateView.as_view(),
         name='practice-update',
         ),
    path("team/<str:slug>/practice/<int:pk>/delete",
         view=views.TeamPracticeDeleteView.as_view(),
         name='practice-delete',
         ),
    path("license/",
         view=views.LicenseListView.as_view(),
         name='licenses-list',
         ),
    path("license/create",
         view=views.LicenseCreateView.as_view(),
         name='license-create',
         ),
    path("license/<int:pk>",
         view=views.LicenseDetailView.as_view(),
         name='license-detail',
         ),
    path("license/<int:pk>/update",
         view=views.LicenseUpdateView.as_view(),
         name='license-update',
         ),
    path("license/<int:pk>/delete",
         view=views.LicenseDeleteView.as_view(),
         name='license-delete',
         ),
]
