# Generated by Django 2.1.7 on 2019-02-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ('season', 'player', 'created'), 'verbose_name': 'license', 'verbose_name_plural': 'licenses'},
        ),
        migrations.AddField(
            model_name='license',
            name='season',
            field=models.CharField(default='2018 / 2019', max_length=12, verbose_name='Season'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='slug',
            field=models.SlugField(default='henri-buyse', max_length=128, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
