# Generated by Django 2.1.7 on 2019-02-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_manager', '0002_auto_20190222_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='recruitment',
            field=models.BooleanField(verbose_name='is recruiting'),
        ),
    ]
