# Generated by Django 2.1.7 on 2019-02-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_manager', '0003_auto_20190222_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymnasium',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'gymnasium'), (1, 'stadium')], default=0, verbose_name='type'),
        ),
    ]
