# Generated by Django 2.1.7 on 2019-04-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_manager', '0003_license_teams_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='teams_names',
            field=models.CharField(blank=True, editable=False, max_length=512, verbose_name='team names'),
        ),
    ]
