# Generated by Django 2.1.7 on 2019-02-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_manager', '0004_gymnasium_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymnasium',
            options={'ordering': ('name', 'zip_code'), 'verbose_name': 'gymnasium', 'verbose_name_plural': 'gymnasiums'},
        ),
        migrations.RenameField(
            model_name='gymnasium',
            old_name='surface',
            new_name='area',
        ),
    ]
