# Generated by Django 2.1.7 on 2019-02-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_manager', '0006_auto_20190225_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ('-created', 'player'), 'verbose_name': 'license', 'verbose_name_plural': 'licenses'},
        ),
        migrations.RemoveField(
            model_name='license',
            name='season',
        ),
    ]
