# Generated by Django 2.0.7 on 2019-03-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_manager', '0007_auto_20190226_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'ordering': ('player', 'first_name', 'last_name'), 'verbose_name': 'emergency contact', 'verbose_name_plural': 'emergency contacts'},
        ),
    ]
