# Generated by Django 2.0.7 on 2019-03-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_manager', '0008_auto_20190312_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('min_age', 'name'), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('category__min_age', 'sex', 'level', 'name'), 'verbose_name': 'team', 'verbose_name_plural': 'teams'},
        ),
    ]
