# Generated by Django 2.0.7 on 2019-03-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_manager', '0009_auto_20190313_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='add_address',
            field=models.CharField(blank=True, max_length=256, verbose_name='additional address'),
        ),
        migrations.AddField(
            model_name='player',
            name='address',
            field=models.CharField(default='5, rue Jean Guy Labarbe', max_length=256, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='city',
            field=models.CharField(default='Nogent-Sur-Marne', max_length=128, verbose_name='city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='zip_code',
            field=models.CharField(default='94130', max_length=5, verbose_name='zip code'),
        ),
        migrations.AlterField(
            model_name='gymnasium',
            name='zip_code',
            field=models.CharField(default='43701', max_length=5, verbose_name='zip code'),
        ),
    ]
