# Generated by Django 2.0.7 on 2019-03-21 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_manager', '0010_auto_20190321_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='player',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='This is not a correct phone number', regex='^(?:(?:\\+|00)33|0)\\s*[1-7,9](?:[\\s.-]*\\d{2}){4}$')], verbose_name='phone number'),
        ),
    ]
