# Generated by Django 2.0.7 on 2019-03-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_manager', '0011_auto_20190321_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='zip_code',
            field=models.CharField(max_length=5, verbose_name='zip code'),
        ),
    ]
