# Generated by Django 2.0.7 on 2019-03-25 12:34

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_manager', '0013_auto_20190322_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='summary',
            field=models.TextField(blank=True, max_length=512, verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, verbose_name='description'),
        ),
    ]
