# Generated by Django 2.1.7 on 2019-03-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_manager', '0015_auto_20190326_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='sex',
            field=models.CharField(choices=[('FE', 'female'), ('MA', 'male')], max_length=2, verbose_name='sex'),
        ),
    ]
