# Generated by Django 2.1.7 on 2019-03-29 10:36

from django.db import migrations, models
import sports_manager.player.models
import sports_manager.player.validators
import sports_manager.storage


class Migration(migrations.Migration):

    dependencies = [
        ('sports_manager', '0016_auto_20190328_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='identity_card',
            field=models.FileField(blank=True, storage=sports_manager.storage.OverwriteStorage(), upload_to=sports_manager.player.models.identity_card_upload_to, validators=[sports_manager.player.validators.validate_file_extension, sports_manager.player.validators.validate_file_size], verbose_name='identity card'),
        ),
        migrations.AddField(
            model_name='player',
            name='identity_photo',
            field=models.ImageField(blank=True, storage=sports_manager.storage.OverwriteStorage(), upload_to=sports_manager.player.models.identity_photo_upload_to, validators=[sports_manager.player.validators.validate_file_extension, sports_manager.player.validators.validate_file_size], verbose_name='identity photo'),
        ),
    ]
