# Generated by Django 2.1.7 on 2019-04-01 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_manager', '0017_auto_20190329_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalcertificate',
            options={'ordering': ('player', '-start', 'validation'), 'verbose_name': 'medical certificate', 'verbose_name_plural': 'medical certificates'},
        ),
    ]
